import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-secondary-100 dark:bg-secondary-800 antialiased text-secondary-900 dark:text-secondary-100 font-light"
    >
      <body className={manrope.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
