import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-secondary-100 dark:bg-secondary-800">
      <body
        className={`${inter.className} antialiased text-secondary-900 dark:text-secondary-100 font-light`}
      >
        {children}
      </body>
    </html>
  );
}
